global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Archivos de reglas de alertas (opcional)
rule_files:
  - "django_alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'django-smartfile'
    static_configs:
      - targets: ['smartfile.railway.internal:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    
    headers:
      X-Prometheus-Token: '${PROMETHEUS_TOKEN}'
    
    # Etiquetas adicionales para identificar la app
    relabel_configs:
      - target_label: 'app'
        replacement: 'smartfile'
      - target_label: 'environment'
        replacement: 'production'
